### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by masiorama** [globalia/craft-recaptcha-v3#1]
Hello, your plugin could be useful for a legacy project (Craft CMS 2 with PHP 7.1) I have to recover.
I am able to install teh module, to configure it with recaptcha keys, but the first  example snippet to place in the head is not working for me,  since the recaptcha floating badge is not visible (nor the recaptcha url asset is loaded).

Can you help me somehow? Is this still active? 

Thanks in advance!

**Comment by masiorama** [comment]
I managed to make it work removing `and renderReCaptcha | default` from the first line in the first example.
I searched for any relevant piece of code named `renderReCaptcha` but no luck... is it a typo?

One more question: the `data-action="contact"` i relevant? I am working with a form whose action is `users/saveUser`, the two things should be related?

Thanks!

**Comment by NancyLussier** [comment]
Hi masiorama,

I've updated the README.md for clearer explanations. The `and renderReCaptcha | default` is useful only if you want to ouput reCAPTCHA on specific templates. The variable must be set, otherwise it will always be false (because the | default value is not set, it will be null). Look in the template section in the README.md for more details.

The data-action="contact" is relevant, since it's the action sent to reCAPTCHA to segment data from possible multiple forms on your site.

Don't hesitate if you have any further questions.

**Comment by masiorama** [comment]
@NancyLussier thanks, now everything is clear to me.

**Comment by masiorama** [comment]
@NancyLussier actually I have to ask for your help again.
It doesn't seem to work, it seems to me that the recaptcha error is never triggered despite the score treshold.
I implemented it here [link ](https://www.bingeeatingdisorders.com/#register).
THe hidden input is displayed, the badge is correctly loaded, the head script are loaded.
If I set treshold to 0 or 1 there is no difference.
Can you give me a hint please?

**Comment by NancyLussier** [comment]
@masiorama I just tested it with a score of 1 and it failed. The problem is that most of the time, we have a score of 0.9. As the comparison includes the threshold, it will be a success if threshold is set to 0.9 and my score is also 0.9. I checked your website and the form action is "users/saveUser", so you have to verify reCAPTCHA score on this event instead of formerly or a&m forms mentioned in README.md.

I didn't test this code, but it will give you the idea : 
```
if (craft()->recaptchaV3->getSecretKey()) {
    craft()->on('users.onBeforeSaveUser', function(Event $event) {
        $user = $event->params['user'];

        if (! craft()->recaptchaV3->verify(craft()->request->getPost('g-recaptcha-response', null))) {
            $event->performAction = false;
            $user->addError('email', Craft::t('recaptcha.error.message'));
        }
    });
}
```

The perform action will stop the process, won't save the user and will assign an error to the user email field. It's the simplest way, as it is a bot anyway.

Hope it will help,

Nancy

**Comment by masiorama** [comment]
@NancyLussier just to get it clear, do I have to develop a plugin and then use the _onBeforeSaveUser_ event to intercept the saving of the form before it is actually sent and then trigger the error as you mentioned just in case?
Thanks again!

**Comment by NancyLussier** [comment]
You can put the event code in your own custom plugin or in craft/plugins/recaptchav3/RecaptchaV3Plugin.php to replace the Formerly example (so all the code related to reCAPTCHA is at the same place). As there's no specific field for reCAPTCHA validation (that could be an idea for better user friendly solution) neither the form plugin used (Formerly, a&m forms or in your case, custom to save a user), you must indeed adapt it to suit your needs.
